version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    platform: linux/amd64
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,lambda, apigateway, ssm, sqs, cloudformation, iam, logs, glue, sns
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker-reuse
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock